name: 'astrafy_project'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
    +schema: Astrafy
    +materialized: view